# Generated by Django 5.2.4 on 2025-08-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_codigoverificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreguntaFallada',
        ),
    ]
