# Generated by Django 5.2.4 on 2025-08-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_delete_preguntafallada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['numero']},
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='fuente_justificacion',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='articulo_justificacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='nombre_oficial',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('oposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='tests.oposicion')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('oposicion', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='tema',
            name='bloque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='tests.bloque'),
        ),
        migrations.AlterUniqueTogether(
            name='tema',
            unique_together={('bloque', 'numero')},
        ),
        migrations.RemoveField(
            model_name='tema',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='oposicion',
        ),
    ]
