# Generated by Django 5.2.4 on 2025-08-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_tema_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oposicion',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
