# Generated by Django 5.2.4 on 2025-08-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_oposicion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='es_premium',
            field=models.BooleanField(default=True),
        ),
    ]
