# Generated by Django 5.2.4 on 2025-08-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_tema_es_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='oposicion',
            name='descripcion_general',
            field=models.TextField(blank=True, help_text='Mensaje motivante que aparece sobre los botones.', null=True),
        ),
        migrations.AddField(
            model_name='oposicion',
            name='info_adicional',
            field=models.TextField(blank=True, help_text='Texto para el tercer recuadro (destino, promoción interna, etc.).', null=True),
        ),
        migrations.AddField(
            model_name='oposicion',
            name='info_convocatoria',
            field=models.TextField(blank=True, help_text='Texto para el recuadro de la convocatoria.', null=True),
        ),
        migrations.AddField(
            model_name='oposicion',
            name='requisitos',
            field=models.TextField(blank=True, help_text='Texto para el recuadro de requisitos.', null=True),
        ),
        migrations.AddField(
            model_name='oposicion',
            name='url_boe',
            field=models.URLField(blank=True, help_text='Enlace al BOE de la convocatoria.', null=True),
        ),
    ]
