# Generated by Django 5.2.4 on 2025-08-20 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_add_slug_to_tema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('tema', 'Tema'), ('repaso', 'Repaso')], max_length=20)),
                ('preguntas_ids', models.JSONField(blank=True, default=list)),
                ('idx_actual', models.PositiveIntegerField(default=0)),
                ('respuestas', models.JSONField(blank=True, default=dict)),
                ('tiempo_restante', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('abandonado', 'Abandonado'), ('finalizado', 'Finalizado')], default='en_curso', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'estado'], name='tests_tests_user_id_5c12d9_idx'), models.Index(fields=['updated_at'], name='tests_tests_updated_79cd80_idx')],
            },
        ),
    ]
