# Generated by Django 5.2.4 on 2025-08-21 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_alter_tema_slug_testsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='tipo',
            field=models.CharField(choices=[('tema', 'Tema'), ('repaso', 'Repaso'), ('examen', 'Examen oficial')], max_length=20),
        ),
        migrations.CreateModel(
            name='ExamenOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Examen oficial', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('preguntas_bloque1', models.PositiveIntegerField(default=60)),
                ('preguntas_bloque2', models.PositiveIntegerField(default=50)),
                ('duracion_minutos', models.PositiveIntegerField(default=90)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('oposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='tests.oposicion')),
            ],
            options={
                'ordering': ['-creado_en'],
                'unique_together': {('oposicion', 'slug')},
            },
        ),
    ]
