# Generated by Django 5.2.4 on 2025-09-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_alter_testsession_tipo_examenoficial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamenOficial',
        ),
    ]
